apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-service.fullname" . }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "order-service.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "order-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "classpath:/application.yml,/config/application.yml"
            - name: SERVER_PORT
              value: "{{ .Values.config.port }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.config.profile }}"
            - name: LOGGING_LEVEL_ROOT
              value: "{{ .Values.config.loggingLevel }}"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Values.config.databaseHost }}:{{ .Values.config.databasePort }}/{{ .Values.config.databaseName }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: order-secrets
                  key: DATABASE_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secrets
                  key: DATABASE_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.config.kafkaBootstrapServers }}"
            - name: PAYMENT_SERVICE_URL
              value: "{{ .Values.config.paymentServiceUrl }}"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: order-secrets
                  key: JWT_SECRET
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 10 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
      volumes:
        - name: config-volume
          configMap:
            name: order-config
            items:
              - key: application.yml
                path: application.yml