apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.secrets.databaseUser | b64enc }}
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | b64enc }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc }}