apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.secrets.databaseUser | b64enc }}
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | b64enc }}
  PG_API_KEY: {{ .Values.secrets.pgApiKey | b64enc }}
  PG_SECRET_KEY: {{ .Values.secrets.pgSecretKey | b64enc }}