# 18-payment-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
