apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.frontend }}
  labels:
    app: order-payment-system
    tier: frontend
    {{- include "order-payment-system.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.orderService }}
  labels:
    app: order-payment-system
    tier: backend
    {{- include "order-payment-system.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.paymentService }}
  labels:
    app: order-payment-system
    tier: backend
    {{- include "order-payment-system.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.database }}
  labels:
    app: order-payment-system
    tier: data
    {{- include "order-payment-system.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.messageQueue }}
  labels:
    app: order-payment-system
    tier: messaging
    {{- include "order-payment-system.labels" . | nindent 4 }}
---
  {{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.monitoring }}
  labels:
    app: order-payment-system
    tier: monitoring
    {{- include "order-payment-system.labels" . | nindent 4 }}
  {{- end }}