apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: {{ .Values.namespaces.paymentService }}
  labels:
    app: payment-service
    {{- include "order-payment-system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.paymentService.replicaCount }}
  selector:
    matchLabels:
      app: payment-service
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.deploymentStrategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deploymentStrategy.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: "{{ .Values.global.imageRegistry }}/payment-service:{{ .Values.paymentService.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.paymentService.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: {{ .Values.services.payment.port }}
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "classpath:/application.yml,/config/application.yml"
            - name: SERVER_PORT
              value: "{{ .Values.services.payment.port }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.global.environment }}"
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Values.services.paymentdb.name }}.{{ .Values.namespaces.database }}.svc.cluster.local:5432/{{ .Values.paymentdb.auth.database }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: DATABASE_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: DATABASE_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.services.kafka.name }}.{{ .Values.namespaces.messageQueue }}.svc.cluster.local:9092"
            - name: PG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: PG_API_KEY
            - name: PG_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: PG_SECRET_KEY
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            {{- toYaml .Values.paymentService.resources | nindent 10 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.services.payment.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.services.payment.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
      volumes:
        - name: config-volume
          configMap:
            name: payment-config
            items:
              - key: application.yml
                path: application.yml