apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.frontend.name }}
  namespace: {{ .Values.namespaces.frontend }}
  labels:
    app: frontend
    {{- include "order-payment-system.labels" . | nindent 4 }}
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.services.frontend.port }}
      targetPort: {{ .Values.services.frontend.port }}
      protocol: TCP
  type: ClusterIP