apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.order.name }}
  namespace: {{ .Values.namespaces.orderService }}
  labels:
    app: order-service
    {{- include "order-payment-system.labels" . | nindent 4 }}
spec:
  selector:
    app: order-service
  ports:
    - port: {{ .Values.services.order.port }}
      targetPort: {{ .Values.services.order.port }}
      protocol: TCP
  type: ClusterIP