apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.payment.name }}
  namespace: {{ .Values.namespaces.paymentService }}
  labels:
    app: payment-service
    {{- include "order-payment-system.labels" . | nindent 4 }}
spec:
  selector:
    app: payment-service
  ports:
    - port: {{ .Values.services.payment.port }}
      targetPort: {{ .Values.services.payment.port }}
      protocol: TCP
  type: ClusterIP