apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.namespaces.frontend }}
  labels:
    {{- include "order-payment-system.labels" . | nindent 4 }}
data:
  REACT_APP_API_URL: "http://{{ .Values.services.order.name }}.{{ .Values.namespaces.orderService }}.svc.cluster.local:{{ .Values.services.order.port }}"
  REACT_APP_ENVIRONMENT: "{{ .Values.global.environment }}"
  REACT_APP_VERSION: "{{ .Chart.AppVersion }}"
  nginx.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;
    
      location / {
        try_files $uri $uri/ /index.html;
      }
    
      location /api/orders {
        proxy_pass http://{{ .Values.services.order.name }}.{{ .Values.namespaces.orderService }}.svc.cluster.local:{{ .Values.services.order.port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    
      location /api/payments {
        proxy_pass http://{{ .Values.services.payment.name }}.{{ .Values.namespaces.paymentService }}.svc.cluster.local:{{ .Values.services.payment.port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }