apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: {{ .Values.namespaces.orderService }}
  labels:
    {{- include "order-payment-system.labels" . | nindent 4 }}
data:
  APPLICATION_PORT: "{{ .Values.services.order.port }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.global.environment }}"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "INFO"
  DATABASE_HOST: "{{ .Values.services.orderdb.name }}.{{ .Values.namespaces.database }}.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "{{ .Values.orderdb.auth.database }}"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.services.kafka.name }}.{{ .Values.namespaces.messageQueue }}.svc.cluster.local:9092"
  PAYMENT_SERVICE_URL: "http://{{ .Values.services.payment.name }}.{{ .Values.namespaces.paymentService }}.svc.cluster.local:{{ .Values.services.payment.port }}"
  application.yml: |
    server:
      port: {{ .Values.services.order.port }}
    
    spring:
      application:
        name: order-service
      datasource:
        url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics