auth:
  username: orderuser
  database: orderdb
  existingSecret: order-db-credentials

primary:
  persistence:
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m