auth:
  username: orderuser
  database: orderdb
  existingSecret: order-db-credentials

primary:
  persistence:
    size: 50Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m
  replicaCount: 1