apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespaces.database }}
  labels:
    {{- include "order-payment-system.labels" . | nindent 4 }}
type: Opaque
data:
  # 초기 설치 시 사용될 기본 비밀번호
  postgres-password: {{ randAlphaNum 16 | b64enc | quote }}
  user-password: {{ randAlphaNum 16 | b64enc | quote }}