apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespaces.database }}
  labels:
    {{- include "order-payment-system.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretData := dict }}
    {{- $oldSecret := lookup "v1" "Secret" .Values.namespaces.database "db-credentials" }}
    {{- if $oldSecret }}
    # 기존 비밀번호 유지
    {{- $secretData = $oldSecret.data }}
    {{- else }}
    # 초기 설치 시 새 비밀번호 생성
    {{- $_ := set $secretData "postgres-password" (randAlphaNum 16 | b64enc) }}
    {{- $_ := set $secretData "user-password" (randAlphaNum 16 | b64enc) }}
    {{- end }}
    {{- toYaml $secretData | nindent 2 }}