apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  namespace: {{ .Values.namespaces.orderService }}
  labels:
    {{- include "order-payment-system.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.orderdb.auth.username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.orderdb.auth.password | b64enc }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc }}