apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: {{ .Values.namespaces.paymentService }}
  labels:
    {{- include "order-payment-system.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.paymentdb.auth.username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.paymentdb.auth.password | b64enc }}
  PG_API_KEY: {{ .Values.secrets.pgApiKey | b64enc }}
  PG_SECRET_KEY: {{ .Values.secrets.pgSecretKey | b64enc }}