# 2-frontend-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  REACT_APP_API_URL: "http://order-service.order-service.svc.cluster.local:8080"
  REACT_APP_ENVIRONMENT: "production"
  REACT_APP_VERSION: "1.0.0"
  nginx.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;
      
      location / {
        try_files $uri $uri/ /index.html;
      }
      
      location /api/orders {
        proxy_pass http://order-service.order-service.svc.cluster.local:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
      
      location /api/payments {
        proxy_pass http://payment-service.payment-service.svc.cluster.local:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
