# 6-order-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  namespace: order-service
type: Opaque
data:
  # Base64 인코딩된 값: echo -n "your-value" | base64
  DATABASE_USER: b3JkZXJ1c2Vy            # orderuser
  DATABASE_PASSWORD: b3JkZXJwYXNzd29yZA==  # orderpassword
  JWT_SECRET: b3JkZXJzZXJ2aWNlLWp3dC1zZWNyZXQta2V5LTEyMzQ1Ng==  # orderservice-jwt-secret-key-123456
