# 7-payment-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: payment-service
type: Opaque
data:
  # Base64 인코딩된 값
  DATABASE_USER: cGF5bWVudHVzZXI=            # paymentuser
  DATABASE_PASSWORD: cGF5bWVudHBhc3N3b3Jk      # paymentpassword
  PG_API_KEY: cGctdGVzdC1hcGkta2V5LTEyMzQ1Njc4OTA=  # pg-test-api-key-1234567890
  PG_SECRET_KEY: cGctdGVzdC1zZWNyZXQta2V5LWFiY2RlZmdoaWprMTIzNDU2Nzg5MA==  # pg-test-secret-key-abcdefghijk1234567890
