# 8-db-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: database
type: Opaque
data:
  # 주문 DB 자격 증명
  ORDER_DB_USER: b3JkZXJ1c2Vy            # orderuser
  ORDER_DB_PASSWORD: b3JkZXJwYXNzd29yZA==  # orderpassword
  ORDER_DB_ROOT_PASSWORD: b3JkZXJyb290cGFzcw==  # orderrootpass
  
  # 결제 DB 자격 증명
  PAYMENT_DB_USER: cGF5bWVudHVzZXI=            # paymentuser
  PAYMENT_DB_PASSWORD: cGF5bWVudHBhc3N3b3Jk      # paymentpassword
  PAYMENT_DB_ROOT_PASSWORD: cGF5bWVudHJvb3RwYXNz  # paymentrootpass
