apiVersion: v2
name: order-payment-system
description: A Helm chart for Order Payment System
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: ~12.2.2
    repository: https://charts.bitnami.com/bitnami
    alias: orderdb
    condition: orderdb.enabled
  - name: postgresql
    version: ~12.2.2
    repository: https://charts.bitnami.com/bitnami
    alias: paymentdb
    condition: paymentdb.enabled
  - name: kafka
    version: ~20.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled