# 글로벌 설정
global:
  environment: dev
  domain: order-payment.example.com
  imageRegistry: yourregistry

# 네임스페이스 설정
namespaces:
  frontend: frontend
  orderService: order-service
  paymentService: payment-service
  database: database
  messageQueue: message-queue
  monitoring: monitoring

# 주문 데이터베이스 설정
orderdb:
  enabled: true
  namespaceOverride: "database"  # 이 부분 추가
  auth:
    username: orderuser
    password: orderpassword
    database: orderdb
  # ... 나머지 설정 ...

# 결제 데이터베이스 설정
paymentdb:
  enabled: true
  namespaceOverride: "database"  # 이 부분 추가
  auth:
    username: paymentuser
    password: paymentpassword
    database: paymentdb
  # ... 나머지 설정 ...

# Kafka 설정
kafka:
  enabled: true
  namespaceOverride: "message-queue"  # 이 부분 추가
  replicaCount: 1
  # ... 나머지 설정 ...

# ... 나머지 설정 ...